version: "3.7"
services:
  app:
    build: .
    working_dir: /usr/src/app/www
    volumes:
      - ./:/usr/src/app
    # command: ["tail", "-f", "/dev/null"]
    command: ["npm", "run", "start"]
    environment:
      - USER=0
    ports:
      - "8080:8080"
